export function emitBaseLayout(title: string, headExtra: string, stylesheets: string[]): string {
  const linkTags = stylesheets
    .map((href) => `    <link rel="stylesheet" href="${href}" />`)
    .join("\n");
  const headBlock = [headExtra, linkTags].filter(Boolean).join("\n");

  return `---
const title = ${JSON.stringify(title || "Converted site")};
---
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{title}</title>
${headBlock ? `${headBlock}\n` : ""}    <slot name="head" />
  </head>
  <body>
    <slot />
  </body>
</html>
`;
}

export function emitPageAstro(
  bodyHtml: string,
  headHtml: string,
  options: { title?: string; imports?: string[] } = {},
): string {
  const imports = [
    'import BaseLayout from "../layouts/BaseLayout.astro";',
    ...(options.imports ?? []),
  ];
  const frontmatter = ["---", ...imports, "---", ""];
  const parts = [...frontmatter];

  if (options.title) {
    parts.push(
      `<Fragment slot="head"><title>${escapeHtmlText(options.title)}</title></Fragment>`,
      "",
    );
  }
  if (headHtml.trim()) {
    parts.push(`<Fragment slot="head">${headHtml}</Fragment>`, "");
  }

  parts.push("<BaseLayout>", bodyHtml.trim(), "</BaseLayout>");

  return parts.join("\n");
}

function escapeHtmlText(value: string): string {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export function emitProjectPackageJson(): string {
  return JSON.stringify(
    {
      name: "converted-astro-site",
      type: "module",
      private: true,
      scripts: {
        dev: "astro dev",
        build: "astro build",
        preview: "astro preview",
      },
      dependencies: {
        astro: "6.3.7",
        "@astrojs/cloudflare": "^12.0.0",
      },
      devDependencies: {
        wrangler: "^4.0.0",
      },
    },
    null,
    2,
  );
}

export function emitAstroConfig(): string {
  return `import { defineConfig } from "astro/config";
import cloudflare from "@astrojs/cloudflare";

export default defineConfig({
  output: "server",
  adapter: cloudflare(),
});
`;
}

export function emitWranglerConfig(): string {
  return `{
  "name": "converted-astro-site",
  "compatibility_date": "2025-01-01",
  "main": "./dist/_worker.js/index.js"
}
`;
}

export function emitComponentAstro(
  html: string,
  scopedCss?: string,
  props?: Array<{ name: string }>,
): string {
  const frontmatter = ["---"];
  if (props?.length) {
    frontmatter.push("interface Props {");
    for (const prop of props) {
      frontmatter.push(`  ${prop.name}: string;`);
    }
    frontmatter.push("}");
    frontmatter.push(`const { ${props.map((prop) => prop.name).join(", ")} } = Astro.props;`);
  }
  frontmatter.push("---", "", html.trim());
  const parts = [...frontmatter];
  if (scopedCss?.trim()) {
    parts.push("", "<style>", scopedCss.trim(), "</style>");
  }
  return parts.join("\n");
}

export function emitReadme(): string {
  return `# Converted Astro site (SSR / Cloudflare)

Generated by html-to-astro.

\`\`\`bash
pnpm install --config.dangerouslyAllowAllBuilds=true
pnpm dev
pnpm build
npx wrangler dev
\`\`\`

All pages use server-side rendering (\`output: "server"\`) with \`@astrojs/cloudflare\`.
`;
}
