overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

allowBuilds:
  esbuild: true
  heroui-pro: true
  "@heroui-pro/react": true
  heroui-native-pro: true

minimumReleaseAge: 0
